[project]
name = "notebooks"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pandas",
    "nbformat",
    "openpyxl",
    "matplotlib",
    "seaborn",
    "ipykernel",
    "ipywidgets",
    "streamlit"
]
